### ISSUE TITLE
adapt to new ostree-container ociarchive

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-releng-automation#145]
For https://github.com/coreos/fedora-coreos-tracker/issues/812

https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/2919/
```
Exception: Importing failed: Command '['ostree', '--repo=/tmp/tmp6cohmf6g', 'show', '469e3824769141206cd483e351661a53855c60102c4ef04a34b1de7cb20b0089', '--print-metadata-key=version']' returned non-zero exit status 1.
```
This is *another* copy of code like https://github.com/coreos/coreos-assembler/pull/2487

**Comment by dustymabe** [comment]
hmm is `--mode=bare-user` right? the tarballs we have today are `mode=archive-z2`
