### ISSUE TITLE
release-metadata: track parent-sibling relationship

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-releng-automation#15]
In the context of topological-sorting the update-graph in Cincinnati, it would be useful to have a parent-sibling relationship exposed by the build process.

Right now we have an array in the release-index which sorted according to insertion time, oldest to newest.
The pipeline also tracks the parent version for each new release, so it could augment the release metadata by injecting a parent-reference as a new field.

(Some stable topological ordering between releases will required by a few update policies, e.g. update barriers)

/cc @jlebon

**Comment by jlebon** [comment]
So, `meta.json` includes this now, see: https://github.com/coreos/fedora-coreos-pipeline/blob/8e1d80b7d289b7ab1939e1a0d47f1e39bda30351/Jenkinsfile#L166.

So I think it's a matter of updating `coreos-meta-translator` to pass it through to `release.json`?

**Comment by lucab** [comment]
In order to streamline Cincinnati logic, we decided not source this piece of metadata, and instead rely on the already available and equivalent ordering in release-index. Closing.
