### ISSUE TITLE
[secaudit,tagger,info] Bare raise

### ISSUE THREAD

**Issue by puiterwijk** [coreos/fedora-coreos-releng-automation#21]
Rev: `06275b45306167c7ee86649dc6936bb637138850`
File: `coreos-koji-tagger/coreos_koji_tagger.py`
Line: 207

Bare raise is used outside of a `try`/`catch` block.
This will trigger a `TypeError`, since Python will try to raise the last raised exception, which will most likely be `None`.

**Comment by dustymabe** [comment]
So I do want to raise an exception because that particular situation should never happen. Should I just update it to `raise Exception(f"The specified keytab file does not exist: {self.keytab_file}")` ?

**Comment by puiterwijk** [comment]
Yep. Use a non-bare raise.
