### ISSUE TITLE
coreos-koji-tagger: handle koji restarts gracefully

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-releng-automation#46]
Right now if Koji restarts, we just lose auth. We should detect this somehow and e.g. re-auth as needed.

**Comment by dustymabe** [comment]
Yep. This happened to us recently when koji was updated/restarted: https://pagure.io/fedora-infrastructure/issue/8244

**Comment by dustymabe** [comment]
until we fix it (soon!) you can get around this in two ways:

- start a new build and the new build will trigger a new rollout (easy)
- delete project and re-create it (big hammer)
   - you'll need [2FA set up](https://fedoraproject.org/wiki/Infrastructure_Two_Factor_Auth) 
   - log in to `batcave01.phx2.fedoraproject.org` (make sure you have [ssh-config set up](https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-guide/sops/sshaccess.html))
   - execute `sudo rbac-playbook -l os_masters[0] -t delete openshift-apps/coreos-koji-tagger.yml`       
   - execute `sudo rbac-playbook -l os_masters[0] openshift-apps/coreos-koji-tagger.yml`

**Comment by bgilbert** [comment]
@dustymabe After the new rollout, will coreos-koji-tagger automatically tag the packages that it missed?

**Comment by dustymabe** [comment]
> @dustymabe After the new rollout, will coreos-koji-tagger automatically tag the packages that it missed?

Not currently, but I have thought it would be a good idea to do.. Opened an RFE for it: https://github.com/coreos/fedora-coreos-releng-automation/issues/51

**Comment by jlebon** [comment]
See follow-up issue to this in https://github.com/coreos/fedora-coreos-releng-automation/issues/70.
